// -------------------------------------------------------------
// 
// File Name: hdlsrc\lab1\PROCESSING_UNIT_tb.v
// Created: 2022-10-25 20:35:04
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Y                             ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PROCESSING_UNIT_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PROCESSING_UNIT_tb;



  reg  i_CLK;
  reg  i_RST_N;
  wire i_CLK_EN;
  wire Y_done;  // ufix1
  wire rdEnb;
  wire Y_done_enb;  // ufix1
  reg [19:0] Y_addr;  // ufix20
  wire Y_active;  // ufix1
  reg [19:0] Data_Type_Conversion_out1_addr;  // ufix20
  wire [19:0] Data_Type_Conversion7_out1_addr_delay_1;  // ufix20
  reg  tb_enb_delay;
  reg signed [31:0] fp_X3;  // sfix32
  reg signed [7:0] rawData_X3;  // int8
  reg signed [31:0] status_X3;  // sfix32
  reg signed [7:0] holdData_X3;  // int8
  reg signed [7:0] X3_offset;  // int8
  wire signed [7:0] X3;  // int8
  wire [19:0] Data_Type_Conversion6_out1_addr_delay_1;  // ufix20
  reg signed [31:0] fp_W3;  // sfix32
  reg signed [7:0] rawData_W3;  // int8
  reg signed [31:0] status_W3;  // sfix32
  reg signed [7:0] holdData_W3;  // int8
  reg signed [7:0] W3_offset;  // int8
  wire signed [7:0] W3;  // int8
  wire [19:0] Data_Type_Conversion5_out1_addr_delay_1;  // ufix20
  reg signed [31:0] fp_X2;  // sfix32
  reg signed [7:0] rawData_X2;  // int8
  reg signed [31:0] status_X2;  // sfix32
  reg signed [7:0] holdData_X2;  // int8
  reg signed [7:0] X2_offset;  // int8
  wire signed [7:0] X2;  // int8
  wire [19:0] Data_Type_Conversion4_out1_addr_delay_1;  // ufix20
  reg signed [31:0] fp_W2;  // sfix32
  reg signed [7:0] rawData_W2;  // int8
  reg signed [31:0] status_W2;  // sfix32
  reg signed [7:0] holdData_W2;  // int8
  reg signed [7:0] W2_offset;  // int8
  wire signed [7:0] W2;  // int8
  wire [19:0] Data_Type_Conversion3_out1_addr_delay_1;  // ufix20
  reg signed [31:0] fp_X1;  // sfix32
  reg signed [7:0] rawData_X1;  // int8
  reg signed [31:0] status_X1;  // sfix32
  reg signed [7:0] holdData_X1;  // int8
  reg signed [7:0] X1_offset;  // int8
  wire signed [7:0] X1;  // int8
  wire [19:0] Data_Type_Conversion2_out1_addr_delay_1;  // ufix20
  reg signed [31:0] fp_W1;  // sfix32
  reg signed [7:0] rawData_W1;  // int8
  reg signed [31:0] status_W1;  // sfix32
  reg signed [7:0] holdData_W1;  // int8
  reg signed [7:0] W1_offset;  // int8
  wire signed [7:0] W1;  // int8
  wire [19:0] Data_Type_Conversion1_out1_addr_delay_1;  // ufix20
  reg signed [31:0] fp_X0;  // sfix32
  reg signed [7:0] rawData_X0;  // int8
  reg signed [31:0] status_X0;  // sfix32
  reg signed [7:0] holdData_X0;  // int8
  reg signed [7:0] X0_offset;  // int8
  wire signed [7:0] X0;  // int8
  wire Data_Type_Conversion_out1_active;  // ufix1
  wire Data_Type_Conversion_out1_enb;  // ufix1
  wire [19:0] Data_Type_Conversion_out1_addr_delay_1;  // ufix20
  reg signed [31:0] fp_W0;  // sfix32
  reg signed [7:0] rawData_W0;  // int8
  reg signed [31:0] status_W0;  // sfix32
  reg signed [7:0] holdData_W0;  // int8
  reg signed [7:0] W0_offset;  // int8
  wire signed [7:0] W0;  // int8
  reg  check1_done;  // ufix1
  wire snkDonen;
  wire tb_enb;
  wire ce_out;
  wire signed [15:0] Y;  // int16
  wire Y_enb;  // ufix1
  wire Y_lastAddr;  // ufix1
  wire [19:0] Y_addr_delay_1;  // ufix20
  reg signed [31:0] fp_Y_expected;  // sfix32
  reg signed [15:0] Y_expected;  // int16
  reg signed [31:0] status_Y_expected;  // sfix32
  wire signed [15:0] Y_ref;  // int16
  reg  Y_testFailure;  // ufix1
  wire testFailure;  // ufix1


  assign Y_done_enb = Y_done & rdEnb;



  assign Y_active = Y_addr != 20'b11110100001001000000;



  assign #1 Data_Type_Conversion7_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for X3
  initial
    begin : X3_fileread
      fp_X3 = $fopen("X3.dat", "r");
      status_X3 = $rewind(fp_X3);
    end

  always @(Data_Type_Conversion7_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_X3 <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_X3 = $fscanf(fp_X3, "%h", rawData_X3);
      end
    end

  // holdData reg for Data_Type_Conversion7_out1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : stimuli_Data_Type_Conversion7_out1
      if (!i_RST_N) begin
        holdData_X3 <= 8'bx;
      end
      else begin
        holdData_X3 <= rawData_X3;
      end
    end

  always @(rawData_X3 or rdEnb)
    begin : stimuli_Data_Type_Conversion7_out1_1
      if (rdEnb == 1'b0) begin
        X3_offset <= holdData_X3;
      end
      else begin
        X3_offset <= rawData_X3;
      end
    end

  assign #2 X3 = X3_offset;

  assign #1 Data_Type_Conversion6_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for W3
  initial
    begin : W3_fileread
      fp_W3 = $fopen("W3.dat", "r");
      status_W3 = $rewind(fp_W3);
    end

  always @(Data_Type_Conversion6_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_W3 <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_W3 = $fscanf(fp_W3, "%h", rawData_W3);
      end
    end

  // holdData reg for Data_Type_Conversion6_out1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : stimuli_Data_Type_Conversion6_out1
      if (!i_RST_N) begin
        holdData_W3 <= 8'bx;
      end
      else begin
        holdData_W3 <= rawData_W3;
      end
    end

  always @(rawData_W3 or rdEnb)
    begin : stimuli_Data_Type_Conversion6_out1_1
      if (rdEnb == 1'b0) begin
        W3_offset <= holdData_W3;
      end
      else begin
        W3_offset <= rawData_W3;
      end
    end

  assign #2 W3 = W3_offset;

  assign #1 Data_Type_Conversion5_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for X2
  initial
    begin : X2_fileread
      fp_X2 = $fopen("X2.dat", "r");
      status_X2 = $rewind(fp_X2);
    end

  always @(Data_Type_Conversion5_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_X2 <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_X2 = $fscanf(fp_X2, "%h", rawData_X2);
      end
    end

  // holdData reg for Data_Type_Conversion5_out1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : stimuli_Data_Type_Conversion5_out1
      if (!i_RST_N) begin
        holdData_X2 <= 8'bx;
      end
      else begin
        holdData_X2 <= rawData_X2;
      end
    end

  always @(rawData_X2 or rdEnb)
    begin : stimuli_Data_Type_Conversion5_out1_1
      if (rdEnb == 1'b0) begin
        X2_offset <= holdData_X2;
      end
      else begin
        X2_offset <= rawData_X2;
      end
    end

  assign #2 X2 = X2_offset;

  assign #1 Data_Type_Conversion4_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for W2
  initial
    begin : W2_fileread
      fp_W2 = $fopen("W2.dat", "r");
      status_W2 = $rewind(fp_W2);
    end

  always @(Data_Type_Conversion4_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_W2 <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_W2 = $fscanf(fp_W2, "%h", rawData_W2);
      end
    end

  // holdData reg for Data_Type_Conversion4_out1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : stimuli_Data_Type_Conversion4_out1
      if (!i_RST_N) begin
        holdData_W2 <= 8'bx;
      end
      else begin
        holdData_W2 <= rawData_W2;
      end
    end

  always @(rawData_W2 or rdEnb)
    begin : stimuli_Data_Type_Conversion4_out1_1
      if (rdEnb == 1'b0) begin
        W2_offset <= holdData_W2;
      end
      else begin
        W2_offset <= rawData_W2;
      end
    end

  assign #2 W2 = W2_offset;

  assign #1 Data_Type_Conversion3_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for X1
  initial
    begin : X1_fileread
      fp_X1 = $fopen("X1.dat", "r");
      status_X1 = $rewind(fp_X1);
    end

  always @(Data_Type_Conversion3_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_X1 <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_X1 = $fscanf(fp_X1, "%h", rawData_X1);
      end
    end

  // holdData reg for Data_Type_Conversion3_out1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : stimuli_Data_Type_Conversion3_out1
      if (!i_RST_N) begin
        holdData_X1 <= 8'bx;
      end
      else begin
        holdData_X1 <= rawData_X1;
      end
    end

  always @(rawData_X1 or rdEnb)
    begin : stimuli_Data_Type_Conversion3_out1_1
      if (rdEnb == 1'b0) begin
        X1_offset <= holdData_X1;
      end
      else begin
        X1_offset <= rawData_X1;
      end
    end

  assign #2 X1 = X1_offset;

  assign #1 Data_Type_Conversion2_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for W1
  initial
    begin : W1_fileread
      fp_W1 = $fopen("W1.dat", "r");
      status_W1 = $rewind(fp_W1);
    end

  always @(Data_Type_Conversion2_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_W1 <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_W1 = $fscanf(fp_W1, "%h", rawData_W1);
      end
    end

  // holdData reg for Data_Type_Conversion2_out1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : stimuli_Data_Type_Conversion2_out1
      if (!i_RST_N) begin
        holdData_W1 <= 8'bx;
      end
      else begin
        holdData_W1 <= rawData_W1;
      end
    end

  always @(rawData_W1 or rdEnb)
    begin : stimuli_Data_Type_Conversion2_out1_1
      if (rdEnb == 1'b0) begin
        W1_offset <= holdData_W1;
      end
      else begin
        W1_offset <= rawData_W1;
      end
    end

  assign #2 W1 = W1_offset;

  assign #1 Data_Type_Conversion1_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for X0
  initial
    begin : X0_fileread
      fp_X0 = $fopen("X0.dat", "r");
      status_X0 = $rewind(fp_X0);
    end

  always @(Data_Type_Conversion1_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_X0 <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_X0 = $fscanf(fp_X0, "%h", rawData_X0);
      end
    end

  // holdData reg for Data_Type_Conversion1_out1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : stimuli_Data_Type_Conversion1_out1
      if (!i_RST_N) begin
        holdData_X0 <= 8'bx;
      end
      else begin
        holdData_X0 <= rawData_X0;
      end
    end

  always @(rawData_X0 or rdEnb)
    begin : stimuli_Data_Type_Conversion1_out1_1
      if (rdEnb == 1'b0) begin
        X0_offset <= holdData_X0;
      end
      else begin
        X0_offset <= rawData_X0;
      end
    end

  assign #2 X0 = X0_offset;

  assign Data_Type_Conversion_out1_active = Data_Type_Conversion_out1_addr != 20'b11110100001001000000;



  assign Data_Type_Conversion_out1_enb = Data_Type_Conversion_out1_active & (rdEnb & tb_enb_delay);



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1000000
  always @(posedge i_CLK or negedge i_RST_N)
    begin : DataTypeConversion_process
      if (i_RST_N == 1'b0) begin
        Data_Type_Conversion_out1_addr <= 20'b00000000000000000000;
      end
      else begin
        if (Data_Type_Conversion_out1_enb) begin
          if (Data_Type_Conversion_out1_addr >= 20'b11110100001001000000) begin
            Data_Type_Conversion_out1_addr <= 20'b00000000000000000000;
          end
          else begin
            Data_Type_Conversion_out1_addr <= Data_Type_Conversion_out1_addr + 20'b00000000000000000001;
          end
        end
      end
    end



  assign #1 Data_Type_Conversion_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for W0
  initial
    begin : W0_fileread
      fp_W0 = $fopen("W0.dat", "r");
      status_W0 = $rewind(fp_W0);
    end

  always @(Data_Type_Conversion_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_W0 <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_W0 = $fscanf(fp_W0, "%h", rawData_W0);
      end
    end

  // holdData reg for Data_Type_Conversion_out1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : stimuli_Data_Type_Conversion_out1
      if (!i_RST_N) begin
        holdData_W0 <= 8'bx;
      end
      else begin
        holdData_W0 <= rawData_W0;
      end
    end

  always @(rawData_W0 or rdEnb)
    begin : stimuli_Data_Type_Conversion_out1_1
      if (rdEnb == 1'b0) begin
        W0_offset <= holdData_W0;
      end
      else begin
        W0_offset <= rawData_W0;
      end
    end

  assign #2 W0 = W0_offset;

  assign snkDonen =  ~ check1_done;



  assign tb_enb = i_RST_N & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge i_CLK or negedge i_RST_N)
    begin : u_enable_delay
      if (!i_RST_N) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (check1_done == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 i_CLK_EN = rdEnb;

  initial
    begin : i_RST_N_gen
      i_RST_N <= 1'b0;
      # (20);
      @ (posedge i_CLK)
      # (2);
      i_RST_N <= 1'b1;
    end

  always 
    begin : i_CLK_gen
      i_CLK <= 1'b1;
      # (5);
      i_CLK <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        i_CLK <= 1'b1;
        # (5);
        i_CLK <= 1'b0;
        # (5);
        $stop;
      end
    end

  PROCESSING_UNIT u_PROCESSING_UNIT (.i_CLK(i_CLK),
                                     .i_RST_N(i_RST_N),
                                     .i_CLK_EN(i_CLK_EN),
                                     .W0(W0),  // int8
                                     .X0(X0),  // int8
                                     .W1(W1),  // int8
                                     .X1(X1),  // int8
                                     .W2(W2),  // int8
                                     .X2(X2),  // int8
                                     .W3(W3),  // int8
                                     .X3(X3),  // int8
                                     .ce_out(ce_out),
                                     .Y(Y)  // int16
                                     );

  assign Y_enb = ce_out & Y_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1000000
  always @(posedge i_CLK or negedge i_RST_N)
    begin : c_2_process
      if (i_RST_N == 1'b0) begin
        Y_addr <= 20'b00000000000000000000;
      end
      else begin
        if (Y_enb) begin
          if (Y_addr >= 20'b11110100001001000000) begin
            Y_addr <= 20'b00000000000000000000;
          end
          else begin
            Y_addr <= Y_addr + 20'b00000000000000000001;
          end
        end
      end
    end



  assign Y_lastAddr = Y_addr >= 20'b11110100001001000000;



  assign Y_done = Y_lastAddr & i_RST_N;



  // Delay to allow last sim cycle to complete
  always @(posedge i_CLK or negedge i_RST_N)
    begin : checkDone_1
      if (!i_RST_N) begin
        check1_done <= 0;
      end
      else begin
        if (Y_done_enb) begin
          check1_done <= Y_done;
        end
      end
    end

  assign #1 Y_addr_delay_1 = Y_addr;

  // Data source for Y_expected
  initial
    begin : Y_expected_fileread
      fp_Y_expected = $fopen("Y_expected.dat", "r");
      status_Y_expected = $rewind(fp_Y_expected);
    end

  always @(Y_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        Y_expected <= 16'bx;
      end
      else if (ce_out == 1) begin
        status_Y_expected = $fscanf(fp_Y_expected, "%h", Y_expected);
      end
    end

  assign Y_ref = Y_expected;

  always @(posedge i_CLK or negedge i_RST_N)
    begin : Y_checker
      if (i_RST_N == 1'b0) begin
        Y_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && Y !== Y_ref) begin
          Y_testFailure <= 1'b1;
          $display("ERROR in Y at time %t : Expected '%h' Actual '%h'", $time, Y_ref, Y);
        end
      end
    end

  assign testFailure = Y_testFailure;

  always @(posedge i_CLK)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // PROCESSING_UNIT_tb
